name: youtube_api
description: YoutubeAPI is a plugin which directly interects with youtube server. Supports
               Searching video and playlist.
version: 0.5.0
author: NITISH KUMAR SINGH <nitishk2@gmail.com>
homepage: https://github.com/nitishk72/Youtube_API

dependencies:
  flutter:
    sdk: flutter
  http: ">=0.11.3+16 <0.12.0"

flutter:
  plugin:
    androidPackage: io.github.nitishk72.youtubeapi.youtubeapi
    pluginClass: YoutubeApiPlugin
