name: youtube_api
description: YouTubeAPI is a plugin which directly interacts with YouTube
  server. Supports Searching video and playlist.
version: 1.1.0
homepage: https://github.com/nstack-in/youtube_api
repository: https://github.com/nstack-in/youtube_api

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  collection: ^1.15.0
  enum_to_string: ^2.0.1
  iso8601_duration: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
