name: youtube_api_client
description:
  YouTube API Client is a plugin which directly interacts with YouTube
  server. Supports searching videos, channels and playlists.
version: 1.1.0
repository: https://github.com/hyungtaecf/youtube_api

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  collection: ^1.15.0
  enum_to_string: ^2.0.1
  iso8601_duration: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: "Demo"
    path: "screenshots/demo.jpg"

topics:
  - youtube
  - youtubeapi
  - API
  - Video
